// Generated by CoffeeScript 1.3.3
(function() {
  var Player, config, mongoose, _;

  mongoose = require('mongoose');

  _ = require('underscore');

  Player = mongoose.model('Player');

  config = require('../../config/config');

  exports.index = function(req, res) {
    if ((req.user != null) && (req.user.username != null)) {
      Player.findOne({
        username: req.user.username
      }, function(err, player) {
        var key, playerHeroes, value, _ref;
        playerHeroes = new Array();
        _ref = player.heroes;
        for (key in _ref) {
          value = _ref[key];
          playerHeroes.push({
            name: key,
            stones: value.stones,
            level: value.level
          });
        }
        return res.render('modes/main', {
          heroes: playerHeroes,
          heroesCatalog: config.heroes,
          playerJson: player,
          activeSet: player.activeSet,
          level: player.level,
          xp: player.xp,
          username: player.username
        });
      });
    } else {
      res.render('modes/main');
    }
  };

}).call(this);
