// Generated by CoffeeScript 1.3.3
(function() {
  var assets, express, flash, helpers, jsPaths, mongoStore, path;

  express = require('express');

  mongoStore = require('connect-mongo')(express);

  flash = require('connect-flash');

  helpers = require('view-helpers');

  assets = require('connect-assets');

  jsPaths = require("connect-assets-jspaths");

  path = require('path');

  module.exports = function(app, config, passport) {
    console.log('assets directory: ');
    console.log(path.join(__dirname, '../assets'));
    app.set('showStackError', true);
    app.use(express.compress({
      filter: function(req, res) {
        return /json|text|javascript|css/.test(res.getHeader('Content-Type'));
      },
      level: 9
    }));
    app.set('views', config.root + '/app/views');
    app.set('view engine', 'jade');
    app.configure(function() {
      app.use(helpers(config.app.name));
      app.use(express.cookieParser());
      app.use(express.bodyParser());
      app.use(express.methodOverride());
      app.use(express.session({
        secret: 'blutfurblut',
        store: new mongoStore({
          url: config.db,
          collection: 'sessions'
        })
      }));
      app.use(express.favicon(path.join(__dirname, '../assets/img/favicon.ico')));
      app.use(flash());
      app.use(passport.initialize());
      app.use(passport.session());
      app.use(express["static"](path.join(__dirname, '../assets')));
      app.use(assets());
      jsPaths(assets);
      app.use(app.router);
    });
    app.configure('development', function() {
      console.log('Configuring development environment');
      app.use(express.errorHandler());
      app.locals.pretty = true;
    });
  };

}).call(this);
