// Generated by CoffeeScript 1.3.3
(function() {

  exports.requiresLogin = function(req, res, next) {
    if (!req.isAuthenticated()) {
      return res.redirect('/login');
    }
    next();
  };

}).call(this);
