// Generated by CoffeeScript 1.3.3
(function() {

  module.exports = function(app) {
    var marked, moment;
    marked = require('marked');
    app.locals.marked = marked;
    moment = require('moment');
    return app.locals.dateShortMon = function(date) {
      return moment(date).format('MMM DD');
    };
  };

}).call(this);
