// Generated by CoffeeScript 1.3.3
(function() {
  var Article, ArticleSchema, Schema, getTags, mongoose, setTags;

  mongoose = require('mongoose');

  getTags = function(tags) {
    return tags.join(',');
  };

  setTags = function(tags) {
    return tags.split(',');
  };

  Schema = mongoose.Schema;

  ArticleSchema = new Schema({
    title: {
      type: String,
      trim: true,
      required: true
    },
    body: {
      type: String,
      required: true
    },
    tags: {
      type: [],
      get: getTags,
      set: setTags
    },
    createdAt: {
      type: Date,
      "default": Date.now
    }
  });

  ArticleSchema.statics = {
    list: function(cb) {
      this.find().sort({
        createdAt: -1
      }).exec(cb);
    }
  };

  Article = mongoose.model('Article', ArticleSchema);

}).call(this);
